# Generated by Django 3.0.5 on 2020-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='orientation_rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
