# Generated by Django 3.0.5 on 2020-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200909_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
