# Generated by Django 3.0.5 on 2020-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='course',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='specialisation',
            new_name='department',
        ),
        migrations.AddField(
            model_name='feedback',
            name='college',
            field=models.CharField(default='pvg', max_length=1000),
            preserve_default=False,
        ),
    ]
