# Generated by Django 3.0.5 on 2020-09-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20200924_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='orientation',
        ),
    ]
