# Generated by Django 3.0.5 on 2020-09-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_feedback_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='participant_type',
        ),
    ]
