# Generated by Django 3.0.5 on 2020-09-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20200924_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='participant_type',
            field=models.CharField(max_length=10),
        ),
    ]
