# Generated by Django 3.0.5 on 2020-09-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0005_auto_20200929_0533'),
        ('feedback', '0008_auto_20200924_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='orientation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orientations.Orientation'),
            preserve_default=False,
        ),
    ]
