# Generated by Django 3.0.5 on 2020-09-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_feedback_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='orientation',
        ),
    ]
