# Generated by Django 3.0.5 on 2020-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('profile_pic', models.FileField(upload_to='')),
                ('college', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('id_card_pic', models.FileField(upload_to='')),
                ('eyic_flag', models.BooleanField(default=False)),
                ('eyrc_flag', models.BooleanField(default=False)),
                ('eysip_flag', models.BooleanField(default=False)),
                ('eystp_flag', models.BooleanField(default=False)),
                ('eymooc_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
