# Generated by Django 3.0.5 on 2020-10-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrations',
            new_name='Registration',
        ),
    ]
