# Generated by Django 3.0.5 on 2020-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201027_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approve_registration',
            field=models.BooleanField(default=False),
        ),
    ]
