# Generated by Django 3.0.5 on 2020-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='eyic_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eymooc_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eyrc_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eysip_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eystp_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialisation',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
