# Generated by Django 3.0.5 on 2020-10-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyca', '0004_profile_id_card_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='degree',
            new_name='course',
        ),
    ]
