# Generated by Django 3.0.5 on 2020-10-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eyca', '0005_auto_20201026_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(upload_to='')),
                ('college', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('id_card_pic', models.FileField(upload_to='')),
                ('eyic_flag', models.BooleanField(default=False)),
                ('eyrc_flag', models.BooleanField(default=False)),
                ('eysip_flag', models.BooleanField(default=False)),
                ('eystp_flag', models.BooleanField(default=False)),
                ('eymooc_flag', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
