# Generated by Django 3.0.5 on 2020-10-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyca', '0006_registrationrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequests',
        ),
    ]
