# Generated by Django 3.0.5 on 2020-10-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyca', '0007_delete_registrationrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_card_pic',
        ),
    ]
