# Generated by Django 3.0.5 on 2020-09-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_type', models.CharField(max_length=100)),
                ('expected_participants', models.IntegerField()),
                ('outreach', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrientationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_participants', models.IntegerField()),
                ('activities_description', models.CharField(max_length=1000)),
                ('activities_photo', models.FileField(upload_to='')),
                ('other_attachments', models.FileField(upload_to='')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientations.Orientation')),
            ],
        ),
    ]
