# Generated by Django 3.0.5 on 2020-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0002_auto_20200903_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientationreport',
            name='other_attachments',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
