# Generated by Django 3.0.5 on 2020-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0003_auto_20200903_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
